core: TelegramBotAPI/**/*
api_extensions: TelegramBotAPI-extensions-api/**/*
utils_extensions: TelegramBotAPI-extensions-utils/**/*

code_changes: ./**/*.kt
gradle_changes: ./**/*.gradle
markdown_changes: ./**/*.md
