api: "TelegramBotAPI-extensions-api/**"
utils: "TelegramBotAPI-extensions-utils/**"
core: "TelegramBotAPI/**" # currently not work

code: "**/*.kt"
gradle: "**/*.gradle"
versions: "**/gradle.properties"
markdown:
  - "**/*.md"
  - "!CHANGELOG.md"
