api: "TelegramBotAPI-api/**"
utils: "TelegramBotAPI-utils/**"
behaviour-builder: "TelegramBotAPI-behaviour_builder/**"
behaviour-builder_fsm: "TelegramBotAPI-behaviour_builder-fsm/**"
core: "TelegramBotAPI-core/**" # currently not work

code: "**/*.kt"
gradle: "**/*.gradle"
versions: "**/gradle.properties"
markdown:
  - "**/*.md"
  - "!CHANGELOG.md"
