language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk8

jobs:
  include:
    - stage: build
      script: ./gradlew build -s -x jvmTest -x jsTest -x jsBrowserTest -x jsNodeTest
    - state: test
      script: ./gradlew allTests
