name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome with your first issue'
        pr-message: 'Welcome with your first PullRequest'
